FROM python:3.9.5
ADD requirements-dev.txt /
RUN pip install -r /requirements-dev.txt \
 && rm /requirements-dev.txt \
 && mkdir -p /app
ADD server.py client.py Makefile /app/
ADD tests /app/tests/
WORKDIR /app
