name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Build on the oldest supported images, so we have broader compatibility
jobs:
  macOS:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install brew packages
        run: |
          brew update >/dev/null
          brew install pyenv pipenv
      - name: Setup environment and dependencies
        run: |
          env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.8.9
          pipenv sync --dev
      - name: Create binaries
        run: |
          pipenv run pyinstaller -F --noconfirm --hiddenimport mido.backends.rtmidi client.py
          pipenv run pyinstaller -F --noconfirm --hiddenimport mido.backends.rtmidi server.py
      - name: Upload binaries
        run: |
          cd dist
          tar czvf network-midi-hub-osx.tgz client server
      - uses: actions/upload-artifact@v2
        with:
          name: network-midi-hub-osx
          path: build/release/network-midi-hub-osx.tgz
          retention-days: 1

